[0.293s] Invoking command in '/home/kishoreyogaraj/tracking_ws/build/tracking_msgs': CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/home/kishoreyogaraj/tracking_ws/install/tracking:/opt/ros/humble /usr/bin/cmake --build /home/kishoreyogaraj/tracking_ws/build/tracking_msgs -- -j8 -l8
[0.318s] -- Found ament_cmake: 1.3.9 (/opt/ros/humble/share/ament_cmake/cmake)
[0.463s] -- Found rosidl_default_generators: 1.2.0 (/opt/ros/humble/share/rosidl_default_generators/cmake)
[0.465s] -- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
[0.468s] -- Found rosidl_adapter: 3.1.5 (/opt/ros/humble/share/rosidl_adapter/cmake)
[0.499s] -- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
[0.529s] -- Found std_msgs: 4.2.4 (/opt/ros/humble/share/std_msgs/cmake)
[0.595s] -- Found vision_msgs: 4.1.1 (/opt/ros/humble/share/vision_msgs/cmake)
[0.909s] [31mCMake Error at /opt/ros/humble/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:59 (message):
[0.909s]   execute_process(/usr/bin/python3 -m rosidl_adapter --package-name
[0.909s]   tracking_msgs --arguments-file
[0.910s]   /home/kishoreyogaraj/tracking_ws/build/tracking_msgs/rosidl_adapter__arguments__tracking_msgs.json
[0.910s]   --output-dir
[0.910s]   /home/kishoreyogaraj/tracking_ws/build/tracking_msgs/rosidl_adapter/tracking_msgs
[0.910s]   --output-file
[0.910s]   /home/kishoreyogaraj/tracking_ws/build/tracking_msgs/rosidl_adapter/tracking_msgs.idls)
[0.910s]   returned error code 1:
[0.910s] 
[0.910s]   Error processing 'geometry_msgs/PoseWithCovariance Pose' of
[0.911s]   'tracking_msgs/Obstacle': ''Pose' is an invalid field name.  It should have
[0.911s]   the pattern '^(?!.*__)(?!.*_$)[a-z][a-z0-9_]*$''
[0.911s] 
[0.911s]   Traceback (most recent call last):
[0.911s] 
[0.911s]     File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[0.911s]       return _run_code(code, main_globals, None,
[0.911s]     File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
[0.911s]       exec(code, run_globals)
[0.911s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__main__.py", line 19, in <module>
[0.912s]       sys.exit(main())
[0.912s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/main.py", line 53, in main
[0.912s]       abs_idl_file = convert_to_idl(
[0.912s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__init__.py", line 19, in convert_to_idl
[0.912s]       return convert_msg_to_idl(
[0.912s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/msg/__init__.py", line 28, in convert_msg_to_idl
[0.912s]       msg = parse_message_string(package_name, input_file.stem, content)
[0.912s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 519, in parse_message_string
[0.912s]       fields.append(Field(
[0.912s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 354, in __init__
[0.913s]       raise NameError(
[0.913s] 
[0.913s]   NameError: 'Pose' is an invalid field name.  It should have the pattern
[0.913s]   '^(?!.*__)(?!.*_$)[a-z][a-z0-9_]*$'
[0.913s] 
[0.913s] Call Stack (most recent call first):
[0.913s]   /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
[0.913s]   CMakeLists.txt:15 (rosidl_generate_interfaces)
[0.913s] 
[0.913s] [0m
[0.914s] -- Configuring incomplete, errors occurred!
[0.914s] See also "/home/kishoreyogaraj/tracking_ws/build/tracking_msgs/CMakeFiles/CMakeOutput.log".
[0.916s] gmake: *** [Makefile:963: cmake_check_build_system] Error 1
[0.919s] Invoked command in '/home/kishoreyogaraj/tracking_ws/build/tracking_msgs' returned '2': CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/home/kishoreyogaraj/tracking_ws/install/tracking:/opt/ros/humble /usr/bin/cmake --build /home/kishoreyogaraj/tracking_ws/build/tracking_msgs -- -j8 -l8
